adding cumulative infections sa vignette
UQ4covid/uq4covid.github.io pull request #4
Opened 2020-06-01 14:28 UTC by dougmcneall

This is my first pull request so let me know if I've messed anything up. I had problems converting R markdown files to markdown files using the code in the vignette style guide. This might need changing if it's crucial.

2020-06-02 13:08 UTC, sieste requested changes
Hi Doug, Thanks for contributing the vignette. Could you quickly address my comments, then I'll merge your vignette so it shows on the website. Cheers, Stefan

2020-06-02 13:08 UTC, sieste commented on vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd
> +We use a Gaussin process emulator from package DiceKriging to model the variation of cumulative infections at lockdown (23rd March 2020) with parameters. We then run a simple sensitivity analysis, an
Gaussian

2020-06-02 13:08 UTC, sieste commented on vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd
> +Load the cumulative infections by day 79 (23rd March 2020) in local authorities This data has the parameters BUT NOT THE RUN NUMBER or unique ID.
period missing

2020-06-02 13:08 UTC, sieste commented on vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd
> +
any conclusions?

2020-06-02 13:08 UTC, sieste commented on vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd
> +
maybe add a concluding paragraph?

2020-06-03 07:15 UTC, dougmcneall commented
Hi Stefan, I changed the vignette according to your requests and pushed it back to the repo. Did I do it right? Can you see it to merge?

Cheers,

Doug

> On 2 Jun 2020, at 14:09, Stefan Siegert <notifications@github.com> wrote:
> 
> ﻿
> @sieste requested changes on this pull request.
> 
> Hi Doug, Thanks for contributing the vignette. Could you quickly address my comments, then I'll merge your vignette so it shows on the website. Cheers, Stefan
> 
> In vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd:
> 
> > @@ -0,0 +1,279 @@
> +---
> +title: "Sensitivity analysis of COVID cumulative cases at lockdown"
> +author: "Doug McNeall"
> +date: "2020-06-01"
> +output: html_document
> +---
> +
> +
> +This is a preliminary sensitivity analysis to test data, emulators and techniques, and shouldn't be used to draw conclusions. There appears to be at least one design point where MetaWards "breaks", for example infecting more people by lockdown than there are in the population.
> +
> +We use a Gaussin process emulator from package DiceKriging to model the variation of cumulative infections at lockdown (23rd March 2020) with parameters. We then run a simple sensitivity analysis, and an initial history-matching type exercise, comparing the model with external estimates of cumulative cases from Jit et al. (2020).
> Gaussian
> 
> In vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd:
> 
> > +```
> +
> +Load packages and helper functions.  
> +```{r}
> +library(DiceKriging)
> +library(sensitivity)
> +library(RColorBrewer)
> +
> +source("https://raw.githubusercontent.com/dougmcneall/packages-git/master/emtools.R")
> +source("https://raw.githubusercontent.com/dougmcneall/packages-git/master/imptools.R")
> +source("https://raw.githubusercontent.com/dougmcneall/packages-git/master/vistools.R")
> +
> +```
> +
> +
> +Load the cumulative infections by day 79 (23rd March 2020) in local authorities This data has the parameters BUT NOT THE RUN NUMBER or unique ID.  
> period missing
> 
> In vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd:
> 
> > +loo = leaveOneOut.km(fit.national, type = 'UK', trend.reestim = TRUE)
> +loo.mae = mean(abs(loo$mean - y.national))
> +
> +ylim = range(loo$mean - (2*loo$sd),loo$mean + (2*loo$sd) )
> +plot(y.national, loo$mean,
> +     xlab = 'cumulative infections at lockdown', ylab = 'emulator prediction',
> +     main = 'leave-one-out cross validtaion',
> +     pch = 19,
> +     ylim = ylim)
> +segments(x0 = y.national, y0 = loo$mean - (2*loo$sd), x1 = y.national, y1 = loo$mean + (2*loo$sd))
> +legend('topleft', legend = "bars indicate \u00B12 sd", bty = 'n')
> +abline(0,1)
> +
> +
> +```
> +
> any conclusions?
> 
> In vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd:
> 
> > +
> +```
> +
> +
> +Darker shading indicates regions where more samples from the emulator fall within the estimated ranges of cumulative infections. The shapes in parameter space show how the parameters can offset each other.
> +```{r, fig.width = 8, fig.height = 8, warning=FALSE}
> +blues = brewer.pal(9, 'Blues')
> +
> +pairs(X.unif.kept.unnorm[, 1:3],
> +      gap = 0,
> +      panel = dfunc.up,
> +      dfunc.col = blues
> +      )
> +```
> +
> +
> maybe add a concluding paragraph?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-04 08:17 UTC, dougmcneall commented on vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd
> +We use a Gaussin process emulator from package DiceKriging to model the variation of cumulative infections at lockdown (23rd March 2020) with parameters. We then run a simple sensitivity analysis, an
Sorted

2020-06-04 08:17 UTC, dougmcneall commented on vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd
> +Load the cumulative infections by day 79 (23rd March 2020) in local authorities This data has the parameters BUT NOT THE RUN NUMBER or unique ID.
Sorted.

2020-06-04 08:17 UTC, dougmcneall commented on vignettes/cumulative_infections_at_lockdown_sensitivity.Rmd
> +
Added

2020-06-04 09:53 UTC, BayesExeter commented
I see Stefan has been commenting so I'll post a quick reminder, otherwise I'll merge for you as it would be good to have these online. Maybe meeting Leon tomorrow.

2020-06-04 14:28 UTC, dougmcneall commented
I pushed a new version yesterday but Stefan didn’t see it - I may have messed it up? The diffs look ok though. Can you confirm you can see both commits? Stefan hasn’t got back yet.

Doug

> On 4 Jun 2020, at 10:53, BayesExeter <notifications@github.com> wrote:
> 
> ﻿
> I see Stefan has been commenting so I'll post a quick reminder, otherwise I'll merge for you as it would be good to have these online. Maybe meeting Leon tomorrow.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-04 14:42 UTC, BayesExeter requested changes
Hi Doug,
 
So looking closely, I think it's fine, but because other changes have been merged, there would be an issue. Can you pull the latest version of the vignettes.md (the one with the quantile emulator etc) and add to that instead, then recommit.

2020-06-04 14:44 UTC, dougmcneall commented
Ah, ok, might have to do that in a little while (busy with kids) but will complete before tomorrow morning no problems.

> On 4 Jun 2020, at 15:43, BayesExeter <notifications@github.com> wrote:
> 
> ﻿
> @BayesExeter requested changes on this pull request.
> 
> Hi Doug,
> 
> So looking closely, I think it's fine, but because other changes have been merged, there would be an issue. Can you pull the latest version of the vignettes.md (the one with the quantile emulator etc) and add to that instead, then recommit.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-04 17:47 UTC, dougmcneall commented
Would you mind trying a merge? It’s only a line in vignettes.md and I think it should work (it’ll just merge new stuff in?). I’ve looked at the instructions for updating at my end and it would be quicker just to do the whole thing again!

> On 4 Jun 2020, at 15:44, Doug McNeall <dougmcneall@gmail.com> wrote:
> 
> ﻿
> Ah, ok, might have to do that in a little while (busy with kids) but will complete before tomorrow morning no problems.
> 
>>> On 4 Jun 2020, at 15:43, BayesExeter <notifications@github.com> wrote:
>>> 
>> ﻿
>> @BayesExeter requested changes on this pull request.
>> 
>> Hi Doug,
>> 
>> So looking closely, I think it's fine, but because other changes have been merged, there would be an issue. Can you pull the latest version of the vignettes.md (the one with the quantile emulator etc) and add to that instead, then recommit.
>> 
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-04 17:54 UTC, BayesExeter commented
> Would you mind trying a merge? It’s only a line in vignettes.md and I think it should work (it’ll just merge new stuff in?). I’ve looked at the instructions for updating at my end and it would be quicker just to do the whole thing again!
> […](#)

Can't you just correct vignettes.md by hand on GitHub? Take the current master branch copy, select all copy, then paste into your vignettes.md and correct your line. The diff file in your commit seems to suggest we'd lose the additions.

2020-06-04 18:33 UTC, dougmcneall commented
OK, I've tried that, hope it works OK. If not I'll scrub and try the whole thing again.

2020-06-05 07:22 UTC, BayesExeter commented
> OK, I've tried that, hope it works OK. If not I'll scrub and try the whole thing again.

Hi Doug,

I know I'm being a massive pain here, so sorry. The new vignettes.md file you have will not break the existing one :), but also doesn't link in the vignette you want to add. I don't know if you want to add a link or just change the sensitivity analysis link. I think it's fine after that.

2020-06-05 08:51 UTC, dougmcneall commented
No, you're not being a pain - it's just me being stupid *facepalm*

2020-06-05 08:56 UTC, dougmcneall commented
Right, line added in vignettes.md. Hope that does it (and I'm learning how this goes!)

2020-06-05 11:16 UTC, BayesExeter approved these changes
All looks good. Going to merge now and check the site.

2020-06-05 11:17 UTC, merged